### ISSUE TITLE
tuned-adm crash when invoked from ansible

### ISSUE THREAD

**Issue by W1zzardTPU** [redhat-performance/tuned#59] opened 2017-07-24 13:24 UTC
tuned 2.8.0 from Fedora 26

```
Jul 24 13:20:17 node1 tuned[534]: Exception in thread Thread-9:
Jul 24 13:20:17 node1 tuned[534]: Traceback (most recent call last):
Jul 24 13:20:17 node1 tuned[534]:   File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
Jul 24 13:20:17 node1 tuned[534]:     self.run()
Jul 24 13:20:17 node1 tuned[534]:   File "/usr/lib64/python2.7/threading.py", line 757, in run
Jul 24 13:20:17 node1 tuned[534]:     self.__target(*self.__args, **self.__kwargs)
Jul 24 13:20:17 node1 tuned[534]:   File "/usr/lib/python2.7/site-packages/tuned/daemon/daemon.py", line 107, in _thread_code
Jul 24 13:20:17 node1 tuned[534]:     self._unit_manager.start_tuning()
Jul 24 13:20:17 node1 tuned[534]:   File "/usr/lib/python2.7/site-packages/tuned/units/manager.py", line 90, in start_tuning
Jul 24 13:20:17 node1 tuned[534]:     instance.apply_tuning()
Jul 24 13:20:17 node1 tuned[534]:   File "/usr/lib/python2.7/site-packages/tuned/plugins/instance/instance.py", line 73, in apply_tuning
Jul 24 13:20:17 node1 tuned[534]:     self._plugin.instance_apply_tuning(self)
Jul 24 13:20:17 node1 tuned[534]:   File "/usr/lib/python2.7/site-packages/tuned/plugins/base.py", line 251, in instance_apply_tuning
Jul 24 13:20:17 node1 tuned[534]:     self._run_for_each_device(instance, self._instance_apply_dynamic)
Jul 24 13:20:17 node1 tuned[534]:   File "/usr/lib/python2.7/site-packages/tuned/plugins/base.py", line 196, in _run_for_each_device
Jul 24 13:20:17 node1 tuned[534]:     callback(instance, device)
Jul 24 13:20:17 node1 tuned[534]:   File "/usr/lib/python2.7/site-packages/tuned/plugins/base.py", line 313, in _instance_apply_dynamic
Jul 24 13:20:17 node1 tuned[534]:     self._instance_update_dynamic(instance, device)
Jul 24 13:20:17 node1 tuned[534]:   File "/usr/lib/python2.7/site-packages/tuned/plugins/plugin_disk.py", line 183, in _instance_update_dynamic
Jul 24 13:20:17 node1 tuned[534]:     self._change_spindown(instance, device, new_spindown_level)
Jul 24 13:20:17 node1 tuned[534]: UnboundLocalError: local variable 'new_spindown_level' referenced before assignment

```

My ansible task is just executing tuned-adm
- name: Configure tuned
  command: tuned-adm profile throughput-performance

**Comment by olysonek** [comment] 2017-07-24 14:47
Thanks for the report. The following commit should fix it:
https://github.com/redhat-performance/tuned/commit/b776b7420cca949bf1e1e128e2cbbc9348d2345c

**Comment by yarda** [comment] 2017-07-25 16:43
tuned-2.8.0-3.fc26 already in updates-testing, @W1zzardTPU could you check whether it fixes the problem for you?

**Comment by yarda** [comment] 2017-07-27 15:43
I believe the problem is fixed, thus closing this issue. If not, feel free to reopen.

**Closed by yarda** 2017-07-27 15:43 UTC
