### ISSUE TITLE
tuned.service start and deactivated after few seconds

### ISSUE THREAD

**Issue by psypython** [redhat-performance/tuned#394] opened 2021-12-29 16:48 UTC
Hi all,
this happens on a fedora 35, Followed to the T every guide I found online, but all I can get is:

journalctl -u tuned.service
dic 29 17:41:43 psyhome systemd[1]: Started Dynamic System Tuning Daemon.
dic 29 17:42:10 psyhome systemd[1]: Stopping Dynamic System Tuning Daemon...
dic 29 17:42:10 psyhome systemd[1]: tuned.service: Deactivated successfully.
dic 29 17:42:10 psyhome systemd[1]: Stopped Dynamic System Tuning Daemon.

Hope someone will shed some light.

Thank you anyway

**Comment by yarda** [comment] 2022-01-01 16:42
Could you provide:
`systemctl status tuned`

And TuneD log:
`cat /var/log/tuned/tuned.log`

**Comment by yarda** [comment] 2022-01-10 22:37
I am unable to reproduce this problem, Fedora 35, tuned-2.16.0-1.fc35.noarch, python3-3.10.1-2.fc35.x86_64, I kept it for 60 minutes and it's still running OK.

**Comment by yarda** [comment] 2022-01-15 01:43
According to the #396 this maybe caused by the power-profiles-daemon which seems to be now installed by default in Fedora Workstation: https://fedoraproject.org/wiki/Changes/Power_Profiles_Daemon

If you want to use TuneD the solution is to uninstall power-profiles-daemon or disable/mask it.

**Comment by xvitaly** [comment] 2022-02-13 10:45
The problem is pre-installed and enabled by default since Fedora 35 power-profiles-daemon.

Tuned is nonfunctional until power-profiles-daemon package is installed, because power-profiles-daemon.service has the following in its unit file:
```
Conflicts=tuned.service tlp.service auto-cpufreq.service system76-power.service
```

Can be fixed by adding `Conflicts=power-profiles-daemon.service`: https://github.com/redhat-performance/tuned/pull/414

**Closed** 2022-02-15 21:33 UTC
